### ISSUE TITLE
puPlace and dePlace validation error

### ISSUE THREAD

**Issue by fanshan** [yoctu/rtech-struct#7]
When puPlace and dePlace was missing into the Auction entity we have this error

`TypeError: Cannot read property &#39;length&#39; of undefined<br> &nbsp; &nbsp;at /opt/app/node_modules/rtech-struct/structures/auction.js:43:47`

The Auction entity:

```json
[{
      "creator": "DEMO", "target": ["DEMOEX"],
      "key": "publictest1011", "name": "publictest1011",
      "valid_until": "2021-03-20T01:04:04.000Z",
      "dimension": [ "1", "100", "120", "120", "5", "no" ],
      "distance": 500,"vehicles": ["frgr"],
      "visible": "private","notes":"Agency: 82\nOrder type: spot"
    }]
```

**Comment by lvenier** [comment]
fix puPlace and dePlace validation error #11
